FROM judgoo/base-alpine:v0.0.2 as base_builder
FROM alpine:3.13
RUN apk add --no-cache binutils ocaml --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
COPY --from=base_builder /tool/ /tool/
ENV PATH="/tool:${PATH}"
WORKDIR /workspace
ENTRYPOINT ["Judger"]