FROM judgoo/base-debian:v0.0.2 as base_builder
FROM python:2.7.18-slim-buster
RUN pip install --no-cache numpy pandas
COPY --from=base_builder /tool/ /tool/
ENV PATH="/tool:${PATH}"
WORKDIR /workspace
ENTRYPOINT ["Judger"]