FROM judgoo/base-debian:v0.0.1 as base_builder
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
COPY --from=base_builder /tool/ /tool/
ENV PATH="/tool:${PATH}"
WORKDIR /workspace
ENTRYPOINT ["Judger"]