FROM judgoo/base-alpine:v0.0.2 as base_builder
FROM judgoo/vendor-quickjs:v0.0.1 as qjs_builder
FROM alpine:3.13
COPY --from=qjs_builder /out /usr/local/bin/
COPY --from=base_builder /tool/ /tool/
ENV PATH="/tool:${PATH}"
WORKDIR /workspace
ENTRYPOINT ["Judger"]